---
title: "Regresión múltiple"
author: "Dr. Oscar V. De la Torre Torres"
date: "9/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(devtools)) {install.packages('devtools')
  library(devtools)} else {library(devtools)}
if (!require(stargazer)) {install.packages('stargazer')
  library(stargazer)} else {library(stargazer)}
if (!require(stargazer)) {install.packages('stargazer')
  library(stargazer)} else {library(stargazer)}
if (!require(kableExtra)) {install.packages('kableExtra')
  library(kableExtra)} else {library(kableExtra)}
if (!require(ggplot2)) {install.packages('ggplot2')
  library(ggplot2)} else {library(ggplot2)}
if (!require(openxlsx)) {install.packages('openxlsx')
  library(openxlsx)} else {library(openxlsx)}
if (!require(Quandl)) {install.packages('Quandl')
  library(Quandl)} else {library(Quandl)}

```

# Introducción

En este ejercicio se trabajarán con datos de Quandl , relativos al PIB y consumo mexicanos, PIB de EEUU, Canadá y China.

## Extracción de datos de Quandl

```{r quandl}
# Se inicia la sesión con la API key lograda en Quandl
Quandl.api_key("[su api key]")

# Se extraen los datos del consumo ("WWDI/MEX_NE_CON_TOTL_KN") y del PIB ("WWDI/MEX_NY_GDP_MKTP_KN") de la base de datos de Quandl:
seriest=c("WWDI/MEX_NE_CON_TOTL_KN",
          "WWDI/MEX_NY_GDP_MKTP_KN",
          "WWDI/USA_NY_GDP_MKTP_KN",
          "WWDI/CAN_NY_GDP_MKTP_KN",
          "WWDI/CHN_NY_GDP_MKTP_KN")

Qdataor = Quandl(seriest,  # Quandl codes
                  start_date="1990-12-31", # Fecha de inicio
                  end_date="2018-12-31") # Fecha final
# Aquí convertimos a variación porcentual los datos y le cambiamos el nombre a los encabezados:
fechas=Qdataor[,1] # Extraemos las fechas para pegarlas después.
Qdataor=(log(Qdataor[2:nrow(Qdataor),2:ncol(Qdataor)])-
        log(Qdataor[1:(nrow(Qdataor)-1),2:ncol(Qdataor)]))*100
Qdataor=cbind(fechas[2:length(fechas)],Qdataor)
colnames(Qdataor)=c("Fechas","Consumo","PIBMX",
                    "PIBUSA","PIBCAN","PIBCHN")
```
